name: shareticon prod workflows

on:
  push:
    branches:
      - be-release
      
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # JDK 설정
      - name: JDK 17 setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'

      # properties 파일 생성 : application-prod.properties
      - name: create properties
        working-directory: ./src/main/resources
        run: |
          touch application-prod.properties
          echo "${{ secrets.APPLICATION_PROD }}" > application-prod.properties
        shell: bash

      # build
      - name: Build with Gradle
        run: ./gradlew build -x test


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image Processing
        run: |
          docker build -t seondays/shareticon:latest .
          docker push seondays/shareticon:latest

      - name: SSH Processing
        uses: appleboy/ssh-action@v0.1.6
        with: 
          key: ${{secrets.SSH_PRIVATE_KEY}}
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          port: 22

          # bastion host
          proxy_host: ${{secrets.BASTION_HOST}}
          proxy_port: 22
          proxy_username: ${{secrets.BASTION_USER}}
          proxy_key: ${{secrets.BASTION_PRIVATE_KEY}}
          
          script: |
            sudo docker pull seondays/shareticon:latest
            sudo docker-compose down
            sudo docker-compose up -d

          
      
      

